create table items (id bigint generated by default as identity, brand varchar(255) not null, name varchar(255), price float(53) not null check (price>=1000), year_of_creation integer not null check (year_of_creation>=2022), primary key (id));
create table items (id bigint generated by default as identity, brand varchar(255) not null, name varchar(255), price double not null check (price>=1000), year_of_creation integer not null check (year_of_creation>=2022), primary key (id))
create table items (id bigint generated by default as identity, brand varchar(255) not null, name varchar(255), price double not null check (price>=1000), year_of_creation integer not null check (year_of_creation>=2022), primary key (id))
create table roles (id bigint generated by default as identity, name varchar(255), primary key (id))
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table users_roles (user_id bigint not null, role_id bigint not null)
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users
create table items (id bigint generated by default as identity, brand varchar(255) not null, name varchar(255), price double not null check (price>=1000), year_of_creation integer not null check (year_of_creation>=2022), primary key (id))
create table roles (id bigint generated by default as identity, name varchar(255), primary key (id))
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table users_roles (user_id bigint not null, role_id bigint not null)
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users
create table items (id bigint generated by default as identity, brand varchar(255) not null, name varchar(255), price double not null check (price>=1000), year_of_creation integer not null check (year_of_creation>=2022), primary key (id))
create table roles (id bigint generated by default as identity, name varchar(255), primary key (id))
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table users_roles (user_id bigint not null, role_id bigint not null)
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users
create table items (id bigint generated by default as identity, brand varchar(255) not null, name varchar(255), price double not null check (price>=1000), year_of_creation integer not null check (year_of_creation>=2022), primary key (id))
create table roles (id bigint generated by default as identity, name varchar(255), primary key (id))
create table users (id bigint generated by default as identity, password varchar(255), username varchar(255), primary key (id))
create table users_roles (user_id bigint not null, role_id bigint not null)
alter table users_roles add constraint FKj6m8fwv7oqv74fcehir1a9ffy foreign key (role_id) references roles
alter table users_roles add constraint FK2o0jvgh89lemvvo17cbqvdxaa foreign key (user_id) references users
